apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ram-capstone-deployment
  labels:
    app: Ram-capstone-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Ram-capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Ram-capstone-deployment
    spec:
      containers:
        - image: ramrbs1/project6
          imagePullPolicy: Always
          name: Ram-capstone-deployment
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: Ram-capstone-deployment
  labels:
    app: Ram-capstone-deployment
spec:
  type: LoadBalancer
  selector:
    app: Ram-capstone-deployment
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP