version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  
  
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  build-test-push:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t ramrbs1/project6:${CIRCLE_WORKFLOW_ID:0:7} .
            docker run -d --rm --name testapp -p 8081:8080 ramrbs1/project6:${CIRCLE_WORKFLOW_ID:0:7}
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Ram Kumar"* ]]; then
              docker stop testapp
            else
              docker stop testapp
              exit 1
            fi
            echo "CIRCLE CI WORKFLOW ID ${CIRCLE_WORKFLOW_ID:0:7}"
            docker push ramrbs1/project6:${CIRCLE_WORKFLOW_ID:0:7}
            

          
workflows:
  default:
    jobs:
      - lint
      - build-test-push
