version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3
  
  
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source devops/bin/activate
            make lint
  
          no_output_timeout: 30m 
          
  configure-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, Test and Upload docker image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
            docker build -t ramrbs1/project6:latest .
            docker run -d --rm --name testapp -p 8081:8080 ramrbs1/project6:latest
            sleep 5
            docker container ls
            export URL="http://localhost:8081"
            export response=$(curl -s $URL)
            echo "This is response $response"
            if [[ $response == *"Ram Kumar"* ]]; then
              docker stop testapp
            else
              docker stop testapp
              exit 1
            fi
            docker push ramrbs1/project6:latest
            
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: us-west-2
      - run:
          name: Kube cluster
          command: |
            kubectl get services
            
            
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yaml
          resource-name: deployment/Ram-capstone-deployment
          
          
  test-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
      - run:
          name: Kube cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
          
          
            

          
workflows:
  default:
    jobs:
      - lint
      - configure-image:
          requires:
            - lint
      - aws-eks/create-cluster:
          cluster-name: ram-capstone
          aws-region: us-west-2
          requires:
            - configure-image
      - test-cluster:
          cluster-name: ram-capstone
          aws-region: us-west-2
          requires:
            - aws-eks/create-cluster
      - create-deployment:
            cluster-name:  ram-capstone
            aws-region: us-west-2
            requires:
              - test-cluster
      - test-deployment:
          cluster-name:  ram-capstone
          aws-region: us-west-2
          requires:
            - create-deployment              
      - aws-eks/update-container-image:
          cluster-name: ram-capstone
          aws-region: us-west-2
          container-image-updates: 'Ram-capstone-deployment=ramrbs1/project6:latest'
          get-rollout-status: true
          record: true
          requires:
           - test-deployment
          resource-name:  deployment/Ram-capstone-deployment        
          
            
            
#      - aws-eks/delete-cluster:
#          cluster-name: ram-capstone
#          aws-region: us-west-2
#          requires:
#            - aws-eks/update-container-image
